import logging
from typing import Dict
import starlette.types
from fastapi import APIRouter, Request, HTTPException
from mcp.server import Server
from mcp.server.sse import SseServerTransport

from axiom.security.trust.pep import ABACPolicyEngine, PolicyEnforcementPoint

logger = logging.getLogger("mcp-hub")

class MCPHub:
    """
    Registry for MCP servers exposed over SSE via FastAPI.
    Includes Policy Enforcement Point (PEP) for Zero Trust.
    """
    def __init__(self):
        self.servers: Dict[str, Server] = {}
        # Multi-session support: Store transports by session ID
        self.transports: Dict[str, SseServerTransport] = {}
        self.router = APIRouter(prefix="/mcp")
        self.pep = PolicyEnforcementPoint(ABACPolicyEngine())
        self._setup_routes()

    def register_server(self, name: str, server: Server):
        self.servers[name] = server
        logger.info(f"Registered MCP server: {name}")

    def _setup_routes(self):
        @self.router.get("/{server_name}/sse")
        async def sse_endpoint(server_name: str, request: Request):
            if server_name not in self.servers:
                raise HTTPException(status_code=404, detail=f"MCP Server '{server_name}' not found")
            
            agent_did = request.headers.get("X-Agent-DID", "did:axiom:unknown")
            logger.info(f"SSE Connection: {agent_did} -> {server_name}")
            
            server = self.servers[server_name]
            # The session ID will be generated by the transport and included in the messages URL
            transport = SseServerTransport(f"/mcp/{server_name}/messages")
            
            async def sess(scope: starlette.types.Scope, receive: starlette.types.Receive, send: starlette.types.Send):
                async with transport.connect_sse(scope, receive, send) as (read_stream, write_stream):
                    # Link this specific transport instance to its session
                    # Note: We capture the session_id once the connection is established
                    self.transports[transport.session_id] = transport
                    try:
                        await server.run(read_stream, write_stream, server.create_initialization_options())
                    finally:
                        self.transports.pop(transport.session_id, None)

            return await transport.handle_sse(request.scope, request.receive, request._send)

        @self.router.post("/{server_name}/messages")
        async def handle_message(server_name: str, request: Request):
            # Extract sessionId from query params
            session_id = request.query_params.get("sessionId")
            if not session_id or session_id not in self.transports:
                raise HTTPException(status_code=404, detail="MCP Session not found")
            
            transport = self.transports[session_id]
            
            # Zero Trust: Intercept JSON-RPC
            body = await request.json()
            if body.get("method") == "tools/call":
                agent_did = request.headers.get("X-Agent-DID", "did:axiom:unknown")
                params = body.get("params", {})
                tool_name = params.get("name")
                arguments = params.get("arguments", {})
                
                authorized = await self.pep.authorize_tool_call(
                    agent_did, tool_name, server_name, arguments
                )
                
                if not authorized:
                    return {
                        "jsonrpc": "2.0",
                        "id": body.get("id"),
                        "error": {"code": -32000, "message": "Access Denied"}
                    }

            return await transport.handle_post_message(request.scope, request.receive, request._send)

# Global Hub instance
hub = MCPHub()
