import argparse
import asyncio
import json
import logging
from urllib.parse import urlparse

import asyncpg
from pydantic import BaseModel

from axiom.config import settings
from axiom.rag.schema import SchemaRAG

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

async def extract_schema_from_db(db_url: str) -> dict:
    """Extract table structures, foreign keys, and column types from PostgreSQL."""
    conn = await asyncpg.connect(db_url)
    schema = {}
    
    try:
        # 1. Get all user tables in public schema
        tables_query = """
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_type = 'BASE TABLE';
        """
        tables = await conn.fetch(tables_query)
        
        for table_record in tables:
            table_name = table_record['table_name']
            
            # 2. Get columns for this table
            cols_query = """
                SELECT column_name, data_type 
                FROM information_schema.columns 
                WHERE table_name = $1 
                AND table_schema = 'public';
            """
            columns = await conn.fetch(cols_query, table_name)
            col_names = [col['column_name'] for col in columns]
            
            # Formulate a basic DDL approximation
            col_defs = [f"{col['column_name']} {col['data_type']}" for col in columns]
            ddl = f"CREATE TABLE {table_name} ({', '.join(col_defs)})"
            
            # 3. Get foreign keys (Simplified extraction)
            fk_query = """
                SELECT
                    kcu.column_name, 
                    ccu.table_name AS foreign_table_name,
                    ccu.column_name AS foreign_column_name 
                FROM 
                    information_schema.table_constraints AS tc 
                    JOIN information_schema.key_column_usage AS kcu
                      ON tc.constraint_name = kcu.constraint_name
                      AND tc.table_schema = kcu.table_schema
                    JOIN information_schema.constraint_column_usage AS ccu
                      ON ccu.constraint_name = tc.constraint_name
                      AND ccu.table_schema = tc.table_schema
                WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name = $1;
            """
            fks = await conn.fetch(fk_query, table_name)
            foreign_keys = [
                {"column": fk["column_name"], "references": fk["foreign_table_name"]}
                for fk in fks
            ]
            
            schema[table_name] = {
                "ddl": ddl,
                "columns": col_names,
                "foreign_keys": foreign_keys,
                "description": f"Autogenerated schema for table {table_name}.",
            }
            
    finally:
        await conn.close()
        
    return schema

async def run_ingestion(tenant_id: str, db_url: str):
    logger.info(f"Connecting to database for tenant {tenant_id}...")
    try:
        # Extract schema from the target DB
        schema = await extract_schema_from_db(db_url)
        if not schema:
            logger.warning(f"No tables found in the public schema for {db_url}")
            return
            
        logger.info(f"Extracted {len(schema)} tables. Ingesting into ChromaDB...")
        rag = SchemaRAG()
        rag.ingest(tenant_id, schema)
        
        # Save connection details to Control Plane Database (Axiom DB)
        logger.info(f"Saving tenant connection details to Control Plane...")
        cp_conn = await asyncpg.connect(settings.database_url)
        try:
            await cp_conn.execute("""
                INSERT INTO tenants (tenant_id, db_url, custom_rules)
                VALUES ($1, $2, '')
                ON CONFLICT (tenant_id) DO UPDATE 
                SET db_url = EXCLUDED.db_url;
            """, tenant_id, db_url)
        finally:
            await cp_conn.close()

        logger.info(f"Successfully onboarded schema for tenant: {tenant_id}")
        
    except Exception as e:
        logger.error(f"Failed to onboard tenant {tenant_id}: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Axiom CLI: Onboard a new tenant database.")
    parser.add_argument("--tenant", required=True, help="Unique Tenant ID (e.g., 'acme_corp')")
    parser.add_argument("--url", required=True, help="PostgreSQL connection string")
    
    args = parser.parse_args()
    asyncio.run(run_ingestion(args.tenant, args.url))
